definitions:
  services:
    docker:
      memory: 2048

  steps:
    - step: &secrets-scan
        name: Scan for Secrets
        script:
          - pipe: atlassian/git-secrets-scan:1.2.1

    - step: &sonarqube-scan
        name: SonarQube analysis
        image: node:18.12.0
        size: 2x
        script:
          - npm ci
          - npm run test:coverage
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: https://sonarqube.fiibo.digital/
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: -Dsonar.projectKey=${BITBUCKET_REPO_SLUG}

    - step: &unit-test-and-code-build
        name: Unit tests and code build
        image: node:18.12.0
        size: 2x
        caches:
          - node
        script:
          - npm ci
          - npm run test
          - npm run build

pipelines:
  branches:
    feat/*:
      - step:
          <<: *unit-test-and-code-build
          name: Automatic Unit Tests and Build

    development:
      - step:
          <<: *unit-test-and-code-build
          name: Automatic Unit Tests and Build

    master:
      - parallel:
          - step: *secrets-scan
          - step: *sonarqube-scan
