version: '3.9'

services:
  db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: boilerplate
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - boilerplatenet

  api:
    build: .
    ports:
      - "3333:3333"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    environment:
      DATABASE_URL: postgresql://pguser:pgpass@db:5432/boilerplate?schema=public
    links:
      - db
    depends_on:
      - db
    networks:
      - boilerplatenet

networks:
  boilerplatenet:
    driver: bridge

volumes:
  postgres-data:
